version: '3.7'
services:
  golang_coupon_service:
    build: .
    environment:
      DOCKER_ENV: true
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    depends_on:
      - psql_db
      - prometheus
    networks:
      - network-coupon

  psql_db:
    image: postgres:latest
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - network-coupon

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - network-coupon
    depends_on:
      - psql_db

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3000:3000"
    networks:
      - network-coupon

volumes:
  grafana-data:

networks:
  network-coupon:
    driver: bridge